name: gtp_bot

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r ./requirements.txt 
  
  build_and_push_to_docker_hub:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        needs: tests
        steps:
          - uses: actions/checkout@v2 
          - name: Set up Docker Buildx
            run: docker build . -t ssuhotskiy/gpt_bot:latest
          - name: Login to Docker 
            uses: docker/login-action@v1 
            with:
              username: ${{ secrets.DOCKER_USERNAME }} 
              password: ${{ secrets.DOCKER_PASSWORD }}
          - name: Push to Docker Hub
            run: docker push ssuhotskiy/gpt_bot:latest

  deploy:
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub
      if: github.ref == 'refs/heads/master'
      steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 200m
          script: |
            docker stop gpt_bot || true
            docker rm gpt_bot || true
            docker image rm ssuhotskiy/gpt_bot:latest
            docker pull ssuhotskiy/gpt_bot:latest
            touch .env
            echo TOKEN=${{ secrets.TOKEN }} >> .env
            echo OPENAI_KEY=${{ secrets.OPENAI_KEY }} >> .env
            echo admin_ids=${{ secrets.admin_ids }} >> .env
            echo AUTH_TOKEN=${{ secrets.AUTH_TOKEN }} >> .env
            echo KANDINSKY_API=${{ secrets.KANDINSKY_API }} >> .env
            echo KANDINSKY_SECRET_KEY=${{ secrets.KANDINSKY_SECRET_KEY }} >> .env
            echo DEBUG=False >> .env
            docker run --name gpt_bot --env-file ./.env ssuhotskiy/gpt_bot:latest 
            echo Bot started..
            
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.admin_ids }}
        token: ${{ secrets.TOKEN }}
        message: Deploy ${{ github.workflow }} успешно выполнен!
